FROM node:22-slim

WORKDIR /app
RUN chown node:node /app
USER node

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

RUN mkdir -p /app/data

EXPOSE 3000

CMD ["npm", "run", "dev"]
